set(_CATKIN_CURRENT_PACKAGE "my_apriltag")
set(my_apriltag_VERSION "0.0.0")
set(my_apriltag_MAINTAINER "kat <kat@todo.todo>")
set(my_apriltag_PACKAGE_FORMAT "2")
set(my_apriltag_BUILD_DEPENDS "apriltag" "rospy")
set(my_apriltag_BUILD_EXPORT_DEPENDS "apriltag" "rospy")
set(my_apriltag_BUILDTOOL_DEPENDS "catkin")
set(my_apriltag_BUILDTOOL_EXPORT_DEPENDS )
set(my_apriltag_EXEC_DEPENDS "apriltag" "rospy")
set(my_apriltag_RUN_DEPENDS "apriltag" "rospy")
set(my_apriltag_TEST_DEPENDS )
set(my_apriltag_DOC_DEPENDS )
set(my_apriltag_URL_WEBSITE "")
set(my_apriltag_URL_BUGTRACKER "")
set(my_apriltag_URL_REPOSITORY "")
set(my_apriltag_DEPRECATED "")